# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUSuARGGkcVI7Y5XrhbXuXabVuxlg3Nt
"""

# Install necessary libraries (only once in Colab)
!pip install seaborn pandas matplotlib

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load Titanic dataset (available from Seaborn)
df = sns.load_dataset('titanic')

# Display first 5 rows
print("📊 First 5 rows of the dataset:")
display(df.head())

# 🔍 Data structure: columns, types, null values
print("\n📋 Dataset Info:")
df.info()

print("\n❓ Missing Values:")
print(df.isnull().sum())

# 🧮 Summary statistics
print("\n📈 Summary Statistics:")
display(df.describe(include='all'))

# 🎯 Question Examples:
# 1. Does gender affect survival?
# 2. What age group survived the most?
# 3. Did class (1st/2nd/3rd) influence survival?

# 🌈 Visualization 1: Survival Count by Gender
plt.figure(figsize=(6,4))
sns.countplot(x='sex', hue='survived', data=df)
plt.title("Survival by Gender")
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

# 📊 Visualization 2: Age Distribution
plt.figure(figsize=(8,4))
sns.histplot(df['age'].dropna(), kde=True, bins=30)
plt.title("Age Distribution")
plt.show()

# 📊 Visualization 3: Survival by Class
plt.figure(figsize=(6,4))
sns.countplot(x='pclass', hue='survived', data=df)
plt.title("Survival by Class")
plt.legend(title='Survived', labels=['No', 'Yes'])
plt.show()

# 💡 Correlation heatmap
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()