# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUSuARGGkcVI7Y5XrhbXuXabVuxlg3Nt
"""

# Install required library (in Colab this is safe to run)
!pip install requests
!pip install beautifulsoup4

# Import libraries
import requests
from bs4 import BeautifulSoup

# Target URL (free test site)
url = "http://quotes.toscrape.com"

# Send HTTP GET request
response = requests.get(url)

# Parse HTML using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Find all quote blocks
quotes = soup.find_all('div', class_='quote')

# Extract and print quotes and authors
for quote in quotes:
    text = quote.find('span', class_='text').text
    author = quote.find('small', class_='author').text
    print(f'"{text}" - {author}')