# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUSuARGGkcVI7Y5XrhbXuXabVuxlg3Nt
"""

# Install required libraries
!pip install textblob pandas

# Import libraries
from textblob import TextBlob
import pandas as pd

# Sample data (can replace with Amazon reviews, tweets, etc.)
data = {
    'Review': [
        "I love this product! It works great.",
        "Worst experience ever. Not recommended!",
        "It's okay, nothing special.",
        "Amazing quality and fast delivery!",
        "Very disappointed. It broke after one use."
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Function to analyze sentiment
def get_sentiment(text):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity
    if polarity > 0.1:
        return 'Positive'
    elif polarity < -0.1:
        return 'Negative'
    else:
        return 'Neutral'

# Apply sentiment analysis
df['Sentiment'] = df['Review'].apply(get_sentiment)

# Show results
print("🔍 Sentiment Analysis Results:")
display(df)